from __future__ import annotations

from collections.abc import Iterable

from research_os.contracts.metrics import MetricKind
from research_os.metrics.models import (
    ComparisonBasis,
    MetricDefinition,
    MetricInputDefinition,
)


class MetricDefinitionConflictError(ValueError):
    pass


class MetricDefinitionRegistry:
    """Immutable, deterministic registry of implemented metric semantics."""

    __slots__ = ("_definitions", "definitions")
    _definitions: dict[str, MetricDefinition]
    definitions: tuple[MetricDefinition, ...]

    def __init__(self, definitions: Iterable[MetricDefinition] = ()) -> None:
        by_id: dict[str, MetricDefinition] = {}
        for definition in definitions:
            current = by_id.get(definition.metric_id)
            if current is not None and current != definition:
                raise MetricDefinitionConflictError(
                    f"conflicting metric definition: {definition.metric_id}"
                )
            by_id[definition.metric_id] = definition
        ordered = tuple(by_id[key] for key in sorted(by_id))
        object.__setattr__(self, "_definitions", dict(by_id))
        object.__setattr__(self, "definitions", ordered)

    def __setattr__(self, name: str, value: object) -> None:
        raise AttributeError("MetricDefinitionRegistry is immutable")

    def get(self, metric_id: str) -> MetricDefinition | None:
        return self._definitions.get(metric_id)

    def require(self, metric_id: str) -> MetricDefinition:
        definition = self.get(metric_id)
        if definition is None:
            raise KeyError(f"undefined metric: {metric_id}")
        return definition

    def select(self, metric_ids: Iterable[str]) -> MetricDefinitionRegistry:
        return MetricDefinitionRegistry(self.require(metric_id) for metric_id in metric_ids)


def _input(
    fact_id: str,
    role: str,
    *,
    required: bool = True,
) -> MetricInputDefinition:
    return MetricInputDefinition(fact_id=fact_id, role=role, required=required)


def _definition(
    metric_id: str,
    economic_meaning: str,
    formula_id: str,
    output_unit: str,
    inputs: tuple[str, ...],
    *,
    output_kind: MetricKind = "ratio",
    annualization_policy: str | None = None,
    comparison_bases: frozenset[ComparisonBasis] = frozenset(),
    optional_inputs: frozenset[str] = frozenset(),
) -> MetricDefinition:
    return MetricDefinition(
        metric_id=metric_id,
        definition_version="2.0.0",
        economic_meaning=economic_meaning,
        formula_id=formula_id,
        output_kind=output_kind,
        output_unit=output_unit,
        required_inputs=tuple(
            _input(
                fact_id,
                f"input_{index}",
                required=fact_id not in optional_inputs,
            )
            for index, fact_id in enumerate(inputs, start=1)
        ),
        valid_comparison_bases=comparison_bases,
        annualization_policy=annualization_policy,
        accounting_scope_policy="exact",
    )


def builtin_metric_definitions() -> tuple[MetricDefinition, ...]:
    yoy = frozenset({ComparisonBasis.YOY_PERIOD, ComparisonBasis.END_VS_BEGIN})
    definitions = (
        _definition(
            "roe",
            "Return on average equity",
            "average_ratio",
            "percent",
            ("net_profit_parent", "equity_begin", "equity_end"),
        ),
        _definition(
            "net_margin",
            "Parent profit as a share of revenue",
            "safe_ratio",
            "percent",
            ("net_profit_parent", "revenue"),
        ),
        _definition(
            "asset_turnover",
            "Revenue generated by average assets",
            "average_ratio",
            "x",
            ("revenue", "assets_begin", "assets_end"),
        ),
        _definition(
            "equity_multiplier",
            "Average assets relative to average equity",
            "average_to_average_ratio",
            "x",
            ("assets_begin", "assets_end", "equity_begin", "equity_end"),
        ),
        _definition(
            "cash_conversion_parent",
            "Operating cash flow relative to positive parent profit",
            "positive_denominator_ratio",
            "x",
            ("ocf", "net_profit_parent"),
        ),
        _definition(
            "ar_days",
            "Average receivables days",
            "average_turnover_days",
            "days",
            ("ar_begin", "ar_end", "revenue"),
            annualization_policy="reporting_period_days",
        ),
        _definition(
            "inventory_days",
            "Average inventory days",
            "average_turnover_days",
            "days",
            ("inventory_begin", "inventory_end", "cogs"),
            annualization_policy="reporting_period_days",
        ),
        _definition(
            "simple_fcf",
            "Operating cash flow less capital expenditure",
            "difference",
            "currency",
            ("ocf", "capex_cash"),
            output_kind="flow",
        ),
        _definition(
            "fixed_asset_turnover",
            "Revenue generated by average PPE",
            "average_ratio",
            "x",
            ("revenue", "ppe_begin", "ppe_end"),
        ),
        _definition(
            "capex_intensity",
            "Capital expenditure as a share of revenue",
            "safe_ratio",
            "percent",
            ("capex_cash", "revenue"),
        ),
        _definition(
            "dso_days",
            "Receivable days",
            "turnover_days",
            "days",
            ("avg_ar", "revenue"),
            annualization_policy="reporting_period_days",
        ),
        _definition(
            "dio_days",
            "Inventory days",
            "turnover_days",
            "days",
            ("avg_inventory", "cogs"),
            annualization_policy="reporting_period_days",
        ),
        _definition(
            "dpo_days",
            "Payable days",
            "turnover_days",
            "days",
            ("avg_ap", "cogs"),
            annualization_policy="reporting_period_days",
        ),
        _definition(
            "ccc_days",
            "Cash conversion cycle",
            "cash_conversion_cycle_days",
            "days",
            ("avg_ar", "revenue", "avg_inventory", "cogs", "avg_ap"),
            annualization_policy="reporting_period_days",
        ),
        _definition(
            "inventory_turns",
            "Inventory turns for the reporting period",
            "safe_ratio",
            "x",
            ("cogs", "avg_inventory"),
        ),
        _definition(
            "inventory_turns_period",
            "Inventory turns for the reporting period",
            "safe_ratio",
            "x",
            ("cogs", "avg_inventory"),
        ),
        _definition(
            "inventory_turns_annualized",
            "Annualized inventory turns",
            "annualized_ratio",
            "x",
            ("cogs", "avg_inventory"),
            annualization_policy="annualize_365",
        ),
        _definition(
            "nwc_intensity",
            "Net working capital as a share of revenue",
            "working_capital_ratio",
            "percent",
            ("ar", "inventory", "ap", "revenue"),
        ),
        _definition(
            "gross_profit_to_working_capital",
            "Gross profit relative to net working capital",
            "ratio_to_working_capital",
            "percent",
            ("gross_profit", "ar", "inventory", "ap"),
        ),
        _definition(
            "incremental_nwc_intensity",
            "Incremental working capital relative to incremental revenue",
            "comparable_ratio",
            "percent",
            ("delta_nwc", "delta_revenue"),
            comparison_bases=yoy,
        ),
        _definition(
            "short_debt_to_inventory",
            "Short debt relative to inventory",
            "safe_ratio",
            "percent",
            ("short_debt", "inventory"),
        ),
        _definition(
            "short_debt_to_equity",
            "Short debt relative to equity",
            "safe_ratio",
            "percent",
            ("short_debt", "equity"),
        ),
        _definition(
            "interest_to_gross_profit",
            "Interest expense relative to gross profit",
            "safe_ratio",
            "percent",
            ("interest_expense", "gross_profit"),
        ),
        _definition(
            "total_financing_cost_to_gross_profit",
            "Financing cost relative to gross profit",
            "safe_ratio",
            "percent",
            ("financing_cost", "gross_profit"),
        ),
        _definition(
            "factoring_to_ar",
            "Factoring exposure relative to receivables",
            "coalesced_ratio",
            "percent",
            ("factoring_balance", "derecognized_receivables", "ar"),
            optional_inputs=frozenset({"factoring_balance", "derecognized_receivables"}),
        ),
        _definition(
            "working_capital_financing_to_gross_profit",
            "Working-capital financing relative to gross profit",
            "available_sum_ratio",
            "percent",
            (
                "factoring_balance",
                "derecognized_receivables",
                "receivable_transfer_balance",
                "other_working_capital_financing",
                "gross_profit",
            ),
            optional_inputs=frozenset(
                {
                    "factoring_balance",
                    "derecognized_receivables",
                    "receivable_transfer_balance",
                    "other_working_capital_financing",
                }
            ),
        ),
        _definition(
            "credit_impairment_to_gross_profit",
            "Credit impairment relative to gross profit",
            "safe_ratio",
            "percent",
            ("credit_impairment", "gross_profit"),
        ),
        _definition(
            "inventory_impairment_to_gross_profit",
            "Inventory impairment relative to gross profit",
            "safe_ratio",
            "percent",
            ("inventory_impairment", "gross_profit"),
        ),
        _definition(
            "cash_conversion",
            "Operating cash flow relative to positive net profit",
            "positive_denominator_ratio",
            "percent",
            ("ocf", "net_profit"),
        ),
        _definition(
            "revenue_growth_vs_working_capital_growth",
            "Revenue growth less working-capital growth",
            "difference",
            "percent",
            ("revenue_growth", "working_capital_growth"),
            output_kind="delta",
        ),
        _definition(
            "funding_loop_debt_share",
            "Debt contribution to incremental working capital",
            "comparable_ratio",
            "percent",
            ("delta_debt", "delta_nwc"),
            comparison_bases=yoy,
        ),
        _definition(
            "funding_loop_external_share",
            "Debt and external equity contribution to incremental working capital",
            "comparable_sum_ratio",
            "percent",
            ("delta_debt", "external_equity_financing", "delta_nwc"),
            comparison_bases=yoy,
        ),
        _definition(
            "roic",
            "Return on invested capital",
            "safe_ratio",
            "percent",
            ("nopat", "avg_invested_capital"),
        ),
        _definition(
            "incremental_roic",
            "Incremental return on invested capital",
            "safe_ratio",
            "percent",
            ("delta_nopat", "delta_invested_capital"),
        ),
    )
    return tuple(sorted(definitions, key=lambda item: item.metric_id))


def builtin_metric_registry() -> MetricDefinitionRegistry:
    return MetricDefinitionRegistry(builtin_metric_definitions())


__all__ = [
    "MetricDefinitionConflictError",
    "MetricDefinitionRegistry",
    "builtin_metric_definitions",
    "builtin_metric_registry",
]
