"""Verification checks for the v1.6.0 M1 development milestone."""

CHECKS: dict[str, str] = {
    "version_contract": "tests/unit/release/test_v1_6_version_contract.py",
    "artifact_contracts": "tests/unit/contracts",
    "artifact_properties": "tests/property/contracts",
    "typed_engine": "tests/unit/runtime/test_typed_engine_execution.py",
    "module_plan": "tests/unit/runtime/test_module_plan.py",
    "application_unit": "tests/unit/application",
    "application_runtime": "tests/integration/runtime/test_research_application.py",
    "two_phase_runtime": "tests/integration/runtime/test_two_phase_execution.py",
    "plugin_unit": "tests/unit/plugins",
    "plugin_contract": "tests/contract/plugins/test_kpi_provider_contract.py",
    "plugin_runtime": "tests/integration/runtime/test_plugin_services_v2.py",
    "completion": "tests/unit/completion",
    "readiness": "tests/unit/readiness",
    "completion_readiness": "tests/integration/runtime/test_completion_readiness_separation.py",
    "revision_bound_pit": "tests/integration/runtime/test_revision_bound_fact_view.py",
    "historical_runtime_reference": "tests/regression/runtime/test_v1_5_12_characterization.py",
    "historical_report_reference": "tests/regression/reporting/test_v1_5_12_characterization.py",
    "single_executor": "tests/regression/architecture/test_single_executor_v1_6.py",
    "no_post_engine_semantics": "tests/regression/architecture/test_no_post_engine_semantics_v1_6.py",
    "version_authority": "tests/regression/architecture/test_version_authority_v1_6.py",
    "semantic_claims": "tests/unit/semantics/test_claims.py",
    "valuation_reconciliation": "tests/unit/valuation/test_reconciliation_v1_5_12.py",
}
